### ISSUE TITLE
Custom application launcher and classic menu with double menuitem

### ISSUE THREAD

**Issue by luigifab** [mate-desktop/mate-panel#1227]
#### Actual behaviour
![image](https://user-images.githubusercontent.com/31816829/118365595-ace34300-b59d-11eb-805d-2f9aca8fedc5.png)

#### Steps to reproduce the behaviour
To reproduce the behaviour, right click on a _custom application launcher_ or on _classic menu_ in a mate-panel.
Use the following css in your theme:
 ```css
menuitem label { background:pink; }
menuitem image { background:yellow; }
menuitem check { background:yellow; }
menuitem radio { background:yellow; }
menuitem box { background:orange; }
menuitem > box > menuitem { background:red; }
```
Why the last item use menuitem inside menuitem?

#### MATE general version
1.24.1

#### Package version
1.24.1-1 (http://ftp2.fr.debian.org/debian/pool/main/m/mate-panel/mate-panel_1.24.1-1_amd64.deb)

#### Linux Distribution
Debian Testing
