### ISSUE TITLE
Style of virtual desktop selector applet

### ISSUE THREAD

**Issue by luigifab** [mate-desktop/mate-panel#1461]
With the following CSS code, it's possible to do that (screenshots with gtk 3.24 above and gtk 2.24 below) :

![Image](https://github.com/user-attachments/assets/0f7107a5-6b84-4e9b-9a6c-ea070fda0ca2)

```css
.mate-panel-menu-bar .wnck-pager,
.mate-panel-menu-bar .wnck-applet {
	color: @theme_fg; /* it's the border color of windows */
	background-color: @theme_bg; /* it's the left/right border color » and background color */
}
.mate-panel-menu-bar .wnck-pager:selected,
.mate-panel-menu-bar .wnck-applet .wnck-pager:selected {
	background-color: shade(@theme_selected_bg, 0.7);
}
```

https://github.com/mate-desktop/mate-panel/blob/b0d238cb955c8ea08573aac870b57787fe72683c/applets/wncklet/workspace-switcher.c#L796-L799

But it seems it's impossible to add margin and border.
Is someone know why? and how to do?
