### ISSUE TITLE
Window list - how to theme drag and drop?

### ISSUE THREAD

**Issue by luigifab** [mate-desktop/mate-panel#1463]
When I'm moving an inactive window from the window list of Mate panel, to reorder it, I have a black background, (gray background when it's the active window), how I can theme it?

![Image](https://github.com/user-attachments/assets/eada4665-fab6-4d38-86a7-4152e1d8edc4)

I tried `.dnd { background: yellow; }`, but no...
I tried to search drag and dnd in mate themes, but this didn't help me.

**Comment by lukefromdc** [comment]
I really don't know myself, maybe someone else will see this and have some ideas?

**Comment by luigifab** [comment]
I found a way:

```css
.mate-panel-menu-bar > PanelApplet > wnck-tasklist > button#tasklist-button.flat.toggle { background:transparent; }
.mate-panel-menu-bar > PanelApplet > wnck-tasklist > button { color:inherit; border:0; background:transparent; }
.mate-panel-menu-bar > PanelApplet > wnck-tasklist > * { color:white; border:5px solid blue; background:yellow; }
```

<img width="487" height="427" alt="Image" src="https://github.com/user-attachments/assets/6caddd6d-0905-48cd-8ce0-4286cad079c9" />

And the `*` is working:

<img width="709" height="565" alt="Image" src="https://github.com/user-attachments/assets/c2453555-59db-4ea6-92cd-c63dc0522534" />

And border-radius is also working.
