### ISSUE TITLE
GTK3: Theming issues

### ISSUE THREAD

**Issue by rilian-la-te** [mate-desktop/mate-panel#217]
```C
	MatePanelApplet* applet = MATE_PANEL_APPLET(object);

	/* Rename the class to have compatibility with all GTK2 themes
	 * https://github.com/perberos/Mate-Desktop-Environment/issues/27
	 */
	gtk_widget_set_name(GTK_WIDGET(applet), "PanelApplet");

	mate_panel_applet_register_object (applet);
```

For now this fix is not working (because it set name of the widget, but not name of the class). This bug has 2 solutions:
1. Require separate mate-panel theming
2. Find a way to rename MatePanelApplet class to PanelApplet to theme engine ( to parse themes like this:
```CSS
PanelApplet .button {
    -GtkButton-inner-border: 2;

    border-width: 0 1px;
    border-radius: 0;
    border-color: transparent;
    background-color: @panel_bg_color;
    background-image: none;
    color: @panel_fg_color;
}
```
)
