### ISSUE TITLE
Indicator Applet icon spacing

### ISSUE THREAD

**Issue by zezic** [mate-desktop/mate-panel#796]
#### Expected behaviour
User is able to change applet icon spacing by defining some CSS rules like this:
```css
NaTrayApplet .mate-panel-menu-bar menuitem {
    padding: 0 2px;
}
```

#### Actual behaviour
Icon spacing do not changes. User don't know how to change applet icon spacing. If user apply rule like this:
```css
.mate-panel-menu-bar menuitem {
    padding: 0 2px;
}
```
then rule applies to wide and affects other panel widgets.

#### Steps to reproduce the behaviour
Try to change applet icon spacing.

#### MATE general version
1.20.0

#### Package version
1.20.1-3ubuntu1

#### Linux Distribution
Ubuntu MATE 18.04

#### Link to downstream report of your Distribution
unknown
